name: Build App
on:
  workflow_dispatch:
  
jobs:   
    build_apk:
      strategy:
        matrix: 
          var: ['debug', 'release']
      name: Build APK
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17
            cache: gradle
        - name: Gradlew Permissions
          run: chmod +x ./gradlew
        - name: Assemble ${{matrix.var}} APK
          run: |
            build_type=${{ matrix.var }}
            ./gradlew :app:assemble${build_type^}
        - name: Upload ${{ matrix.var }} APK
          uses: actions/upload-artifact@v4
          with:
            name: apk-${{ matrix.var }}
            path: out/apk-${{matrix.var}}
